### ISSUE TITLE
Trailing slash routing breaks table styles

### ISSUE THREAD

**Issue by svict4** [adamzerella/ausgov#108]
### Problem description

Navigating to a page with a trailing slash breaks styling.
Refreshing a page without a slash reroutes it to one with a slash, and breaks the style.

For easy/lazy debugging: https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-client-only-routes

### Screenshot / Design / File reference

![australiagovau-routing](https://user-images.githubusercontent.com/1137112/44321125-87c35380-a489-11e8-980d-ded8039fb589.gif)

**Comment by azerella** [comment]
Hi @svict4!

Thanks for raising the issue and sorry for our late response. We isolated this problem and resolved it in: https://github.com/govau/ausgov/commit/7e46354eecc1dc8da1e29e25ca4d832a4b569c76. If you have any more suggestions or know of other issues we welcome you to post them 😄
