### ISSUE TITLE
Icons for Index page

### ISSUE THREAD

**Issue by BrendanCNg** [adamzerella/ausgov#28]
### Problem description
Use placeholders for now put in folder 
```
./src/assets
``` 
BUT eventually We need icons for 

- [x] Telephones/area codes
- [x] timezones
- [x] National smbols
- [x] school term dates
- [x] Public Holidays
- [x] Our Country

**Comment by BrendanCNg** [comment]
https://thenounproject.com/

**Comment by adamzerella** [comment]
E.g for school something like: https://thenounproject.com/search/?q=school&i=784564
